import { createFolder, listFileSystem, uploadFile } from "./service";
import type { SessionContext } from "@/core/security/session";
import { format } from "date-fns";

/**
 * Ensures a nested folder path exists in the Explorer.
 * Returns the ID of the leaf folder.
 */
export async function ensureFolderPath(session: SessionContext, path: string): Promise<string | undefined> {
  const parts = path.split("/").filter(p => p.length > 0);
  let currentParentId: string | undefined = undefined;

  for (const part of parts) {
    const { folders } = await listFileSystem(session, currentParentId);
    const existing = folders.find(f => f.name.toLowerCase() === part.toLowerCase());
    
    if (existing) {
      currentParentId = existing.id;
    } else {
      // Create with shared access so everyone in the company can see it
      const result = await apiRequest<any>("/explorer/folders", "POST", session, {
        name: part,
        parent_id: currentParentId,
        access_level: "shared"
      });
      currentParentId = result.id;
    }
  }
  
  return currentParentId;
}

export interface ReportItem {
  sku: string;
  name: string;
  systemCount: number;
  actualCount: number;
  location?: string;
  image?: string;
}

/**
 * Generates and saves a Stock Opname report to the Explorer as a JSON file
 * to enable specialized preview rendering.
 */
export async function saveStockOpnameReport(
  session: SessionContext,
  locationName: string,
  auditorName: string,
  items: ReportItem[]
) {
  const now = new Date();
  const year = format(now, "yyyy");
  const month = format(now, "MMMM");
  const timestamp = format(now, "yyyy-MM-dd_HH-mm");
  
  const folderPath = `${locationName}/${year}/${month}`;
  const folderId = await ensureFolderPath(session, folderPath);
  
  // Save as .json for specialized Explorer preview
  const fileName = `Stock Opname ${locationName} ${timestamp}.json`;
  
  const reportData = {
    items: items.map(item => ({
      sku: item.sku,
      name: item.name,
      expected_quantity: item.systemCount || 0,
      actual_quantity: item.actualCount,
      variance: item.actualCount - (item.systemCount || 0),
      image: item.image,
    }))
  };

  const metadata = {
    type: "STOCK_OPNAME_REPORT",
    location: locationName,
    timestamp: now.toISOString(),
    performer: auditorName,
    ai_name: "Antigravity",
    ai_version: "V1.2.0-Elite"
  };
  
  const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: "application/json" });
  const file = new File([blob], fileName, { type: "application/json" });
  
  const jsonResult = await uploadFile(session, file, folderId, undefined, metadata);

  // 2. Generate and upload Audit Trail (Text Log)
  const auditTrailContent = `STOCK OPNAME AUDIT TRAIL
====================================
Location:  ${locationName}
Auditor:   ${auditorName}
Timestamp: ${now.toLocaleString()}
Status:    COMMITTED
------------------------------------
SUMMARY:
Total Items: ${items.length}
Variances:   ${items.filter(i => i.actualCount !== i.systemCount).length}
------------------------------------
DETAILS:
${items.map(item => `- ${item.name} (${item.sku}): Expected ${item.systemCount || 0}, Actual ${item.actualCount}, Variance ${item.actualCount - (item.systemCount || 0)}`).join("\n")}
====================================
GENERATED BY ZENVIX ROBOTICS
`;

  const logFileName = `Audit Trail ${locationName} ${timestamp}.txt`;
  const logBlob = new Blob([auditTrailContent], { type: "text/plain" });
  const logFile = new File([logBlob], logFileName, { type: "text/plain" });

  await uploadFile(session, logFile, folderId, undefined, {
    ...metadata,
    type: "AUDIT_LOG"
  });

  return jsonResult;
}
