import { Insight, InsightContext, InsightRule } from '../types/insight.types';

export class CashflowDeficitRule implements InsightRule {
  readonly type = 'CASHFLOW_DEFICIT';

  evaluate(context: InsightContext): Insight[] {
    const { cashflow, snapshotSequence, tenant_id, company_id } = context;

    // 1. Find Deficit Markers (Temporally ordered)
    const deficitMarkers = cashflow.riskMarkers
      .filter(m => m.type === 'DEFICIT')
      .sort((a, b) => new Date(a.start_date).getTime() - new Date(b.start_date).getTime());

    if (deficitMarkers.length === 0) {
      return [];
    }

    const marker = deficitMarkers[0];
    const deficitDate = marker.start_date;
    const snapshotDate = new Date(cashflow.snapshotTimestamp);
    const start_date = new Date(deficitDate);

    // 2. Range-Bound Impact Calculation (Patch 1)
    const relevantProjection = cashflow.projectionDetails.filter(p =>
      new Date(p.date).getTime() >= new Date(marker.start_date).getTime() &&
      new Date(p.date).getTime() <= new Date(marker.end_date).getTime()
    );

    const minBalance = relevantProjection.length > 0 
      ? Math.min(...relevantProjection.map(p => p.closingBalance))
      : 0;
    const impactAmount = Math.abs(minBalance);

    // 3. Driver Time Alignment & Selection (Patch 2)
    const eligibleDrivers = cashflow.cashflowDrivers.outflow.filter(d =>
      new Date(d.dueDate).getTime() <= new Date(deficitDate).getTime()
    );

    let driverScope = 'LOCAL_RELIANT';
    let selectedDrivers = eligibleDrivers;

    if (selectedDrivers.length === 0) {
      selectedDrivers = cashflow.cashflowDrivers.outflow;
      driverScope = 'GLOBAL_FALLBACK';
    }

    // Deterministic Selection
    const sortedDrivers = [...selectedDrivers].sort((a, b) => {
      if (b.amount !== a.amount) return b.amount - a.amount;
      return a.id.localeCompare(b.id);
    });

    const selectedDriver = sortedDrivers[0];

    // 4. Explicit Total Cash & Safe Magnitude Weight (Patch 3 & 4)
    const totalCash = cashflow.currentBalance ?? cashflow.projectionDetails[0]?.openingBalance ?? 0;
    const magnitudeWeight = totalCash <= 0 ? 1.0 : Math.min(1.0, impactAmount / totalCash);

    // 5. Time Horizon & Action Priority
    const daysToDeficit = Math.ceil((start_date.getTime() - snapshotDate.getTime()) / (1000 * 3600 * 24));
    const timeHorizon = daysToDeficit <= 7 ? 'IMMEDIATE' : (daysToDeficit <= 30 ? 'SHORT_TERM' : 'MID_TERM');
    const urgencyWeight = timeHorizon === 'IMMEDIATE' ? 2.0 : (timeHorizon === 'SHORT_TERM' ? 1.0 : 0);
    const actionPriority = 4.0 + 3.0 + urgencyWeight + magnitudeWeight;

    // 6. coreInputs Standardization (Patch 6)
    const coreInputs = {
      deficitDate,
      impactAmount: Number(impactAmount.toFixed(2)),
      driverId: selectedDriver?.id || 'SYSTEM_GEN',
      driverAmount: selectedDriver ? Number(selectedDriver.amount.toFixed(2)) : 0
    };

    const message = `Cash deficit of $${impactAmount.toLocaleString()} projected in ${daysToDeficit} days driven by upcoming obligations.`;
    const recommendation = selectedDriver 
      ? `Delay payment ${selectedDriver.documentNumber} ($${selectedDriver.amount.toLocaleString()} due ${selectedDriver.dueDate}) or accelerate receivables to avoid deficit.`
      : `Review all upcoming outflows to bridge the projected $${impactAmount.toLocaleString()} gap within ${daysToDeficit} days.`;

    return [{
      id: '', // Generated by InsightService
      type: this.type,
      scope: 'GLOBAL',
      severity: 'CRITICAL',
      confidence: null, // Computed globally
      timeHorizon,
      actionPriority,
      message,
      recommendation,
      isPrimary: true,
      explanation: {
        rule: 'CashflowDeficitRule',
        inputsUsed: ['riskMarkers', 'projectionDetails', 'cashflowDrivers'],
        coreInputs
      },
      supportingData: {
        deficitStartDate: marker.start_date,
        deficitEndDate: marker.end_date,
        deficitDate,
        impactAmount,
        driverScope,
        driver: selectedDriver ? {
          id: selectedDriver.id,
          documentNumber: selectedDriver.documentNumber,
          amount: selectedDriver.amount,
          dueDate: selectedDriver.dueDate
        } : null
      },
      accountId: selectedDriver?.accountId,
      tenant_id,
      company_id,
      snapshotSequence
    }];
  }

  private getDaysBetween(d1: Date, d2: Date): number {
    return Math.ceil((d1.getTime() - d2.getTime()) / (1000 * 3600 * 24));
  }
}
