const fs = require('fs');
const path = require('path');

const schemaPath = path.join(__dirname, 'prisma/schema.prisma');
let content = fs.readFileSync(schemaPath, 'utf8');

const mapping = {
    'WorkflowRequests': 'workflowRequest',
    'WorkflowInstances': 'workflowInstance',
    'WorkflowAuditEntries': 'workflowAuditEntry',
    'PaymentTransactions': 'paymentTransaction',
    'FinanceArInvoices': 'financeArInvoice',
    'FinanceArCreditMemos': 'financeArCreditMemo',
    'FinanceArPayments': 'financeArPayment',
    'FinanceBankStatements': 'financeBankStatement',
    'FinanceBudgetLines': 'financeBudgetLine',
    'FinanceChartOfAccounts': 'financeChartOfAccount',
    'FinanceJournalEntries': 'financeJournalEntry',
    'FinanceJournalLines': 'financeJournalLine',
    'FinanceLedgerPostings': 'financeLedgerPosting',
    'FinanceTaxConfigs': 'financeTaxConfig',
    'HrAttendanceRecords': 'hrAttendanceRecord',
    'HrBenefitPlans': 'hrBenefitPlan',
    'HrBudgetScenarios': 'hrBudgetScenario',
    'HrCareerPaths': 'hrCareerPath',
    'HrCases': 'hrCase',
    'HrComplianceDocuments': 'hrComplianceDocument',
    'HrComplianceModules': 'hrComplianceModule',
    'HrComplianceReports': 'hrComplianceReport',
    'HrContextSnapshots': 'hrContextSnapshot',
    'HrEmployeeBenefits': 'hrEmployeeBenefit',
    'HrEmployeeSkills': 'hrEmployeeSkill',
    'HrExchangeRates': 'hrExchangeRate',
    'HrHeadcountPlans': 'hrHeadcountPlan',
    'HrHolidays': 'hrHoliday',
    'HrInsights': 'hrInsight',
    'HrMentorshipPairs': 'hrMentorshipPair',
    'HrPayrollRuns': 'hrPayrollRun',
    'HrPerformanceCycles': 'hrPerformanceCycle',
    'HrPerformanceGoals': 'hrPerformanceGoal',
    'HrPositionSkills': 'hrPositionSkill',
    'HrProgramSkills': 'hrProgramSkill',
    'HrRecommendationFeedbacks': 'hrRecommendationFeedback',
    'HrRecommendations': 'hrRecommendation',
    'HrSkills': 'hrSkill',
    'HrSuccessionCandidates': 'hrSuccessionCandidate',
    'HrSuccessionPlans': 'hrSuccessionPlan',
    'HrSystemAlerts': 'hrSystemAlert',
    'HrSystemMetrics': 'hrSystemMetric',
    'HrTalentLeads': 'hrTalentLead',
    'HrThresholdAudits': 'hrThresholdAudit',
    'HrWorkSchedules': 'hrWorkSchedule',
    'InventoryAdjustments': 'inventoryAdjustment',
    'InventoryAlerts': 'inventoryAlert',
    'InventoryAuditCycles': 'inventoryAuditCycle',
    'InventoryMovementRequests': 'inventoryMovementRequest',
    'InventoryPools': 'inventoryPool',
    'InventorySubledgerEntries': 'inventorySubledgerEntry',
    'ItDeviceEvents': 'itDeviceEvent',
    'ItDevices': 'itDevice',
    'ItProvisioningRequests': 'itProvisioningRequest',
    'ItSettings': 'itSetting',
    'ItSystemHealth': 'itSystemHealth',
    'JobRequisitions': 'jobRequisition',
    'JobRoles': 'jobRole',
    'LabelConfigs': 'labelConfig',
    'LeaveRequests': 'leaveRequest',
    'MailAccounts': 'mailAccount',
    'MailLabels': 'mailLabel',
    'MailMessages': 'mailMessage',
    'MailThreads': 'mailThread',
    'MarketingAccounts': 'marketingAccount',
    'MarketingAlerts': 'marketingAlert',
    'MarketingAttribution': 'marketingAttribution',
    'MarketingAuditEvents': 'marketingAuditEvent',
    'MarketingCampaigns': 'marketingCampaign',
    'MarketingExecutions': 'marketingExecution',
    'MarketingLeads': 'marketingLead',
    'MarketingWorkflows': 'marketingWorkflow',
    'ModuleLicenses': 'moduleLicense',
    'MoneySources': 'moneySource',
    'PaymentAuditEvents': 'paymentAuditEvent',
    'PaymentChargebacks': 'paymentChargeback',
    'PaymentDevicePools': 'paymentDevicePool',
    'PaymentDisputes': 'paymentDispute',
    'PaymentEvidencePacks': 'paymentEvidencePack',
    'PaymentPosDevices': 'paymentPosDevice',
    'PaymentProviders': 'paymentProvider',
    'PaymentRefunds': 'paymentRefund',
    'PaymentRetryAttempts': 'paymentRetryAttempt',
    'PaymentRoutingPolicies': 'paymentRoutingPolicy',
    'PaymentSettlements': 'paymentSettlement',
    'PayrollLines': 'payrollLine',
    'PayrollProfiles': 'payrollProfile',
    'PerformanceReviews': 'performanceReview',
    'PosDevices': 'posDevice',
    'ProcurementAuditEvents': 'procurementAuditEvent',
    'ProcurementCategories': 'procurementCategory',
    'ProcurementContracts': 'procurementContract',
    'ProcurementDraftPos': 'procurementDraftPo',
    'ProcurementFinalPos': 'procurementFinalPo',
    'ProcurementRatingLogs': 'procurementRatingLog',
    'ProcurementReceipts': 'procurementReceipt',
    'ProcurementRequisitions': 'procurementRequisition',
    'ProcurementRiskSignals': 'procurementRiskSignal',
    'ProductCategories': 'productCategory',
    'ProductProjections': 'productProjection',
    'RetailCartItems': 'retailCartItem',
    'RetailCarts': 'retailCart',
    'RetailChannels': 'retailChannel',
    'RetailCustomers': 'retailCustomer',
    'RetailOrderItems': 'retailOrderItem',
    'RetailOrders': 'retailOrder',
    'RetailPromotions': 'retailPromotion',
    'RetailShifts': 'retailShift',
    'RetailWishlistItems': 'retailWishlistItem',
    'RetailWishlists': 'retailWishlist',
    'SalesAlerts': 'salesAlert',
    'SalesAuditEvents': 'salesAuditEvent',
    'SalesLeads': 'salesLead',
    'SalesOpportunities': 'salesOpportunity',
    'SalesOrders': 'salesOrder',
    'SalesQuotes': 'salesQuote',
    'SalesTasks': 'salesTask',
    'SalesTimelineEvents': 'salesTimelineEvent',
    'ScheduleAssignments': 'scheduleAssignment',
    'SettlementRecords': 'settlementRecord',
    'ShiftSwapRequests': 'shiftSwapRequest',
    'StockLevels': 'stockLevel',
    'StockMovements': 'stockMovement',
    'StockReservations': 'stockReservation',
    'StockSnapshots': 'stockSnapshot',
    'SupplierBranches': 'supplierBranch',
    'SupplierMasters': 'supplierMaster',
    'SupplierPortalMessages': 'supplierPortalMessage',
    'SupplierProducts': 'supplierProduct',
    'TrainingAssignments': 'trainingAssignment',
    'TrainingPrograms': 'trainingProgram',
    'TreasuryTransfers': 'treasuryTransfer'
};

let newContent = content;
for (const [plural, singular] of Object.entries(mapping)) {
    // Replace plural usage (WorkflowRequests) with singular (workflowRequest)
    // Only in type position: colon or space followed by type
    const regex = new RegExp(`(\\s+)${plural}(\\s|[\\?\\[])`, 'gi');
    newContent = newContent.replace(regex, `$1${singular}$2`);
}

fs.writeFileSync(schemaPath, newContent);
console.log('Absolute Final Plural-to-Singular Fix Applied.');
