export interface Country {
  code: string; // ISO 3166-1 alpha-2  e.g. "ID"
  name: string; // e.g. "Indonesia"
  flag: string; // emoji flag  e.g. "🇮🇩"
  currency: string; // ISO 4217  e.g. "IDR"
  currencyName: string; // e.g. "Indonesian Rupiah"
  symbol: string; // e.g. "Rp"
}

export const COUNTRIES: Country[] = [
  // Southeast Asia
  {
    code: "ID",
    name: "Indonesia",
    flag: "🇮🇩",
    currency: "IDR",
    currencyName: "Indonesian Rupiah",
    symbol: "Rp",
  },
  {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    currency: "SGD",
    currencyName: "Singapore Dollar",
    symbol: "S$",
  },
  {
    code: "MY",
    name: "Malaysia",
    flag: "🇲🇾",
    currency: "MYR",
    currencyName: "Malaysian Ringgit",
    symbol: "RM",
  },
  {
    code: "TH",
    name: "Thailand",
    flag: "🇹🇭",
    currency: "THB",
    currencyName: "Thai Baht",
    symbol: "฿",
  },
  {
    code: "PH",
    name: "Philippines",
    flag: "🇵🇭",
    currency: "PHP",
    currencyName: "Philippine Peso",
    symbol: "₱",
  },
  {
    code: "VN",
    name: "Vietnam",
    flag: "🇻🇳",
    currency: "VND",
    currencyName: "Vietnamese Dong",
    symbol: "₫",
  },
  {
    code: "MM",
    name: "Myanmar",
    flag: "🇲🇲",
    currency: "MMK",
    currencyName: "Myanmar Kyat",
    symbol: "K",
  },
  {
    code: "KH",
    name: "Cambodia",
    flag: "🇰🇭",
    currency: "KHR",
    currencyName: "Cambodian Riel",
    symbol: "៛",
  },
  {
    code: "LA",
    name: "Laos",
    flag: "🇱🇦",
    currency: "LAK",
    currencyName: "Lao Kip",
    symbol: "₭",
  },
  {
    code: "BN",
    name: "Brunei",
    flag: "🇧🇳",
    currency: "BND",
    currencyName: "Brunei Dollar",
    symbol: "B$",
  },
  // East Asia
  {
    code: "CN",
    name: "China",
    flag: "🇨🇳",
    currency: "CNY",
    currencyName: "Chinese Yuan",
    symbol: "¥",
  },
  {
    code: "JP",
    name: "Japan",
    flag: "🇯🇵",
    currency: "JPY",
    currencyName: "Japanese Yen",
    symbol: "¥",
  },
  {
    code: "KR",
    name: "South Korea",
    flag: "🇰🇷",
    currency: "KRW",
    currencyName: "South Korean Won",
    symbol: "₩",
  },
  {
    code: "TW",
    name: "Taiwan",
    flag: "🇹🇼",
    currency: "TWD",
    currencyName: "New Taiwan Dollar",
    symbol: "NT$",
  },
  {
    code: "HK",
    name: "Hong Kong",
    flag: "🇭🇰",
    currency: "HKD",
    currencyName: "Hong Kong Dollar",
    symbol: "HK$",
  },
  // South Asia
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    currency: "INR",
    currencyName: "Indian Rupee",
    symbol: "₹",
  },
  {
    code: "PK",
    name: "Pakistan",
    flag: "🇵🇰",
    currency: "PKR",
    currencyName: "Pakistani Rupee",
    symbol: "₨",
  },
  {
    code: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
    currency: "BDT",
    currencyName: "Bangladeshi Taka",
    symbol: "৳",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    flag: "🇱🇰",
    currency: "LKR",
    currencyName: "Sri Lankan Rupee",
    symbol: "Rs",
  },
  {
    code: "NP",
    name: "Nepal",
    flag: "🇳🇵",
    currency: "NPR",
    currencyName: "Nepalese Rupee",
    symbol: "Rs",
  },
  // Middle East
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    currency: "AED",
    currencyName: "UAE Dirham",
    symbol: "د.إ",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    currency: "SAR",
    currencyName: "Saudi Riyal",
    symbol: "﷼",
  },
  {
    code: "QA",
    name: "Qatar",
    flag: "🇶🇦",
    currency: "QAR",
    currencyName: "Qatari Riyal",
    symbol: "﷼",
  },
  {
    code: "KW",
    name: "Kuwait",
    flag: "🇰🇼",
    currency: "KWD",
    currencyName: "Kuwaiti Dinar",
    symbol: "KD",
  },
  {
    code: "BH",
    name: "Bahrain",
    flag: "🇧🇭",
    currency: "BHD",
    currencyName: "Bahraini Dinar",
    symbol: "BD",
  },
  {
    code: "OM",
    name: "Oman",
    flag: "🇴🇲",
    currency: "OMR",
    currencyName: "Omani Rial",
    symbol: "﷼",
  },
  // Oceania
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    currency: "AUD",
    currencyName: "Australian Dollar",
    symbol: "A$",
  },
  {
    code: "NZ",
    name: "New Zealand",
    flag: "🇳🇿",
    currency: "NZD",
    currencyName: "New Zealand Dollar",
    symbol: "NZ$",
  },
  // Europe
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    currencyName: "British Pound",
    symbol: "£",
  },
  {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    currency: "EUR",
    currencyName: "Euro",
    symbol: "€",
  },
  {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    currency: "EUR",
    currencyName: "Euro",
    symbol: "€",
  },
  {
    code: "IT",
    name: "Italy",
    flag: "🇮🇹",
    currency: "EUR",
    currencyName: "Euro",
    symbol: "€",
  },
  {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    currency: "EUR",
    currencyName: "Euro",
    symbol: "€",
  },
  {
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    currency: "EUR",
    currencyName: "Euro",
    symbol: "€",
  },
  {
    code: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
    currency: "CHF",
    currencyName: "Swiss Franc",
    symbol: "Fr",
  },
  {
    code: "SE",
    name: "Sweden",
    flag: "🇸🇪",
    currency: "SEK",
    currencyName: "Swedish Krona",
    symbol: "kr",
  },
  {
    code: "NO",
    name: "Norway",
    flag: "🇳🇴",
    currency: "NOK",
    currencyName: "Norwegian Krone",
    symbol: "kr",
  },
  {
    code: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    currency: "DKK",
    currencyName: "Danish Krone",
    symbol: "kr",
  },
  {
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    currency: "PLN",
    currencyName: "Polish Złoty",
    symbol: "zł",
  },
  {
    code: "TR",
    name: "Turkey",
    flag: "🇹🇷",
    currency: "TRY",
    currencyName: "Turkish Lira",
    symbol: "₺",
  },
  // Americas
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    currency: "USD",
    currencyName: "US Dollar",
    symbol: "$",
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    currency: "CAD",
    currencyName: "Canadian Dollar",
    symbol: "CA$",
  },
  {
    code: "MX",
    name: "Mexico",
    flag: "🇲🇽",
    currency: "MXN",
    currencyName: "Mexican Peso",
    symbol: "$",
  },
  {
    code: "BR",
    name: "Brazil",
    flag: "🇧🇷",
    currency: "BRL",
    currencyName: "Brazilian Real",
    symbol: "R$",
  },
  {
    code: "AR",
    name: "Argentina",
    flag: "🇦🇷",
    currency: "ARS",
    currencyName: "Argentine Peso",
    symbol: "$",
  },
  {
    code: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    currency: "COP",
    currencyName: "Colombian Peso",
    symbol: "$",
  },
  {
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    currency: "CLP",
    currencyName: "Chilean Peso",
    symbol: "$",
  },
  // Africa
  {
    code: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    currency: "ZAR",
    currencyName: "South African Rand",
    symbol: "R",
  },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    currency: "NGN",
    currencyName: "Nigerian Naira",
    symbol: "₦",
  },
  {
    code: "KE",
    name: "Kenya",
    flag: "🇰🇪",
    currency: "KES",
    currencyName: "Kenyan Shilling",
    symbol: "KSh",
  },
  {
    code: "EG",
    name: "Egypt",
    flag: "🇪🇬",
    currency: "EGP",
    currencyName: "Egyptian Pound",
    symbol: "E£",
  },
];

/** Fast O(1) lookup by ISO code */
export const COUNTRY_MAP: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c]),
);

/** Get currency derived from a country code */
export function getCurrencyForCountry(countryCode: string): string {
  return COUNTRY_MAP[countryCode]?.currency ?? "USD";
}

/** Get full country object or undefined */
export function getCountry(countryCode: string): Country | undefined {
  return COUNTRY_MAP[countryCode];
}
