export enum AccountType {
  ASSET = 'ASSET',
  LIABILITY = 'LIABILITY',
  EQUITY = 'EQUITY',
  REVENUE = 'REVENUE',
  EXPENSE = 'EXPENSE',
}

export enum NormalBalance {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum FiscalPeriodStatus {
  OPEN = 'OPEN',
  SOFT_LOCK = 'SOFT_LOCK',
  HARD_LOCK = 'HARD_LOCK',
  CLOSING = 'CLOSING',
  CLOSED = 'CLOSED',
}

export enum JournalStatus {
  DRAFT = 'DRAFT',
  VALIDATED = 'VALIDATED',
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
}

export enum LedgerPostingStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED', // Legacy
  FAILED_RETRYABLE = 'FAILED_RETRYABLE',
  FAILED_TERMINAL = 'FAILED_TERMINAL',
}

export enum PostingSide {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum PostingRuleStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DRAFT = 'DRAFT',
}

export enum JournalType {
  /** Standard journal created from a business domain event. */
  NORMAL = 'NORMAL',
  /** Mirror-entry that negates a prior NORMAL journal. Immutable on creation. */
  REVERSAL = 'REVERSAL',
  /** Manual correction requiring approver; never auto-generated by the pipeline. */
  ADJUSTMENT = 'ADJUSTMENT',
  /** System-generated journal to zero out P&L accounts during period close. */
  CLOSING = 'CLOSING',
  /** System-generated journal for automated balance repair/reconciliation. */
  SYSTEM_ADJUSTMENT = 'SYSTEM_ADJUSTMENT',
}

export enum JVParticipantRole {
  OPERATOR = 'OPERATOR',
  NON_OPERATOR = 'NON_OPERATOR',
}

export enum JVAllocationType {
  REVENUE = 'REVENUE',
  COST = 'COST',
  PROFIT = 'PROFIT',
}
